### ISSUE TITLE
Add option to change default colors for section, subsection, and subsubsection 

### ISSUE THREAD

**Issue by coatless** [eddelbuettel/pinp#33]
Customize the template by school colors (**cough** orange and blue **cough**)

**Comment by coatless** [comment]
Two new `yaml` variables:

```yaml
# Optional: Font color of the document, values must be in RGB format
text_color: "0,101,165"

# Optional: Set background color, values must be in RGB format
bg_color: "205,217,235"
```

corresponding to:

```latex
\definecolor{pnasbluetext}{RGB}{0,101,165}
\definecolor{pnasblueback}{RGB}{205,217,235} 
```

Recommend colors:

**Red:** 187, 0, 0 
**Green:** 52, 168, 83 
**Blue:** 0, 101, 165
