### ISSUE TITLE
Simplify authors and affiliations

### ISSUE THREAD

**Issue by eddelbuettel** [eddelbuettel/pinp#38]
The current setup is too restrictive and near-broken.  If you remove the affiliations section, only the last of several authors is shown.

It would be nice if you could put a few "if set, then..." layers around it to also allow a _minimal_ use case of just one line of `Author:` with a single entry (or YAML array).

**Comment by saghirb** [comment]
The following in the YAML header seems to resolve the problem:
```
# Use letters for affiliations
author:
  - name: First Author
    affiliation: ~
  - name: Second Author
    affiliation: ~
address:
  - code: ~
    address: ~
```

The spacing seems fine to me too.

### **Multiple authors with affiliation (from the default pinp R markdown document).**
![pinp_with_affiliation](https://user-images.githubusercontent.com/26441369/42934239-97236cfc-8b3e-11e8-877e-241b96049fbe.png)

### **Multiple authors without affiliation (by changing YAML header as above).**
![pinp_without_affiliation](https://user-images.githubusercontent.com/26441369/42934245-9951ca3c-8b3e-11e8-8855-fa0bf7a9a258.png)

**Comment by eddelbuettel** [comment]
So the first example (with address and affiliation) is as before.  The second example shows no code.  

Or is the use of `~` the trick in that it suppresses the affiliation?

**Comment by eddelbuettel** [comment]
Nice. It does :).  Sweet catch!  Now to document this.

**Comment by eddelbuettel** [comment]
Done in 53fc174

**Comment by saghirb** [comment]
Using two single or two double quotes (with or without spaces) also give the same result:
```
# Use letters for affiliations
author:
  - name: First Author
    affiliation: ""
  - name: Second Author
    affiliation: ""
address:
  - code: ""
    address: ""
```

This might be closer to the spirit of how YAML is used with R markdown.
