### ISSUE TITLE
bib.tex not part of package?

### ISSUE THREAD

**Issue by saghirb** [eddelbuettel/pinp#53]
Has the bib.tex file been intentionally omitted from the `pinp` package?

From YAML:
```
# Produce a pinp document
output:
  pinp::pinp:
    includes:
      after_body: bib.tex
```
