### ISSUE TITLE
figure size

### ISSUE THREAD

**Issue by Courvoisier13** [eddelbuettel/pinp#72]
When I do a figure using a

```
> ```{r, fig.pos='H', fig.cap="Text"}
> some ggplot image
> ```

```
the figure text font is too large when compared to the regular text (fontsize 9). In regular markdown, I can control that in the yaml header, ex:

```
output: 
  pdf_document:
    fig_height: 5
    fig_width: 6
```

But pinp does not offer that option. When I set the options:

`knitr::opts_chunk$set(fig.width = 6, fig.height = 5)`

it just increases the size of the figure and goes out of the column.

Is there a way to set fig_height and fig_width of the document?

thanks
