### ISSUE TITLE
reference list indent – change from first line to hanging

### ISSUE THREAD

**Issue by ikashnitsky** [eddelbuettel/pinp#83]
Is there a way to re-format the reference list so that the indentation is hanging, ie
```
Author YEAR ...
    DOI
Another ...
    URL
```
Instead of 
```
    Author YEAR
DOI
    Another ...
URL
```
?
It just looks cleaner and reads easier

**Comment by eddelbuettel** [comment]
What are you using?  I always use _real_ bibliographies with natbib, and that (as I recall) works here too.  As it does eg in every vignette I make with it:  

![image](https://user-images.githubusercontent.com/673121/91110518-b01b5500-e643-11ea-9d57-db26ccbebcf1.png)

That is from package `anytime` which I happen to be debugging something in _right now_.

**Comment by ikashnitsky** [comment]
I found somewhere a hacky way to use custom csl styles with pinp
```
output: 
  bookdown::pdf_book:
    toc: false
    latex_engine: xelatex
    base_format: pinp::pinp
    citation_package: none
    pandoc_args: [ "--csl", "psp.csl" ]
```
The reference list looks like this
<img width="50%" src="https://habrastorage.org/webt/co/ux/iw/couxiwolilxn-qcwg1fdy_hgbyc.png" />
